### ISSUE TITLE
Fix footer

### ISSUE THREAD

**Issue by costateixeira** [hl7-be/hl7.be.fhir.template#9]
The footer is not complete - it is removed except for eHealth IGs - which doesn't make sense.
Suggest to undo the last commit and make a PR quickly . We can do a quick review if useful.

**Comment by bdc-ehealth** [comment]
@costateixeira I think the issue is that the version before #3 used the standard footer of the template (by not including any custom footer at all) and after #3 the template uses the ehealth-footer in the case of eHealth as a publisher, but does not have any alternative for the other cases. See the custom file that was added: https://github.com/hl7-be/hl7.be.fhir.template/blob/master/includes/fragment-footer.html

**Comment by costateixeira** [comment]
Right, that is what I meant - the footer include file is not complete. 
Explanation: by overriding, you removed everything that is in the default footer. And by adding the if statement, the content is only included if the publisher is eHealth. This is not correct, the QA link etc needs to be available especially in the development process.
